### ISSUE TITLE
DSC010 wrong worldmap name

### ISSUE THREAD

**Issue by RoxanneSHS** [Gitjas/DSotSC#11]
http://baldursextendedworld.com/Vanilla_Forums/discussion/comment/2717/#Comment_2717

There is a mismatch in the worldmap/eet/areas.tbl
and the english worldmap.tra
@DS_782004   @DS_782003

I am not providing a pull request because I am not sure how you want the areas named.

Here is my proposal
DSC001      Wood of Sharp Teeth
DSC002      Forgotten Lake
DSC004     Forest of Forgotten Souls
DSC010      Castle Daerthmac

**Comment by RoxanneSHS** [comment]
I have made a patch that uses the area names above on the EET worldmap. However there seems to be an issue when converting the worldmap in EET for the bp-bgt_worldmap mod. There is a missing name for DSC002 and DSC010 is getting the label of DSC004?
I cannot see how the worldmap mod reads the EET tables, but there is some issue there. Uninstalling the worldmap mod and having EET worldmap, there is no problem.

**Comment by RoxanneSHS** [comment]
I found a solution. It took me a bit to find that DSotSC AND BP-BGT-worldmap need to be refined for it to work. So it is unlikely that this will be implemented within foreseeable time.
I put a patch into my Install Tool, so at least people who use it to mod EET can get the benefit.
(It requires an update of "bp-bgt_worldmap\original\tbl\updates\dsotsc_areas.tbl" besides the update in DSotSC.)

**Comment by Gitjas** [comment]
Fixed locally. I settled for the names that are used in the Worldmap mod (which has 7 language versions):
DSC001 is "Wood of Sharp Teeth", DSC002 is "Forest of Forgotten Souls", DSC004 is "East Wood of Sharp Teeth", DSC010 is "Castle Daerthmac"

**Comment by Gitjas** [comment]
Mixed it up in the description here, but not in the mod. The names are:
DSC001 is "Wood of Sharp Teeth", 
DSC002 is "East Wood of Sharp Teeth", 
DSC004 is "Forest of Forgotten Souls", 
DSC010 is "Castle Daerthmac"
