### ISSUE TITLE
BGT: item BAM (inventory) outcentered

### ISSUE THREAD

**Issue by Gitjas** [Gitjas/DSotSC#8]
For the scrolls the BAM if shown in e.g. Thalantyr's store is outcentered so it's nearly not to be seen any more. I think it's for all scrolls, the one I saw were all in Thalantyr's store:
-Ettin's Healing
-Army of One
-Ray of Frost
-Globe of Darkness
-Isebolt
-Thunderslap
-Orb of Air

**Comment by Gitjas** [comment]
I understand now what happened. The two pctures - for "laying in inventory" and "player is picking item up" need to be reversed. This goes for all spell scrolls:
-Ettin's Healing -- DSSPW41A.BAM
-Army of One -- DSSPW32A.BAM
-Ray of Frost -- DSSPW31A.BAM
-Globe of Darkness -- DSSPW23A.BAM
-Isebolt -- DSSPW22A.BAM
-Thunderslap -- DSSPW21A.BAM
-Orb of Air -- DSSPW11A.BAM
-Melf's Explosive Meteors -- DSSPW51A.BAM
-Anti-Magic Shell -- DSSPW62A.BAM
-Mass Charm -- DSSPW72A.BAM
-Vestcakes Floating Curse -- DSSPW74A.BAM
-Infernal Combustion Enigma -- DSSPW81A.BAM
-Thunder Bolt -- DSSPW84A.BAM
-Varashar's Life Drain -- DSSPW85A.BAM

**Comment by Gitjas** [comment]
See also here: http://www.shsforums.net/topic/60436-cosmetic-bugs-of-the-dsotsc-icon-bams/

**Comment by GwendolyneFreddy** [comment]
If you only need to switch frame 0 and frame 1, either you can do it with NI bam converter tool, or with WeiDU if there is a lot a files.

**Comment by Sampsca** [comment]
I have taken a quick look through the BAMs, and the list of issues is long.  Want me to list them all, or just take a crack at them (I've been kind of busy lately so may need some time)?  Most everything I think I can handle, but a few of the spell B/C icons could use a touch-up by a real artist (which I am not).  Is EE compatibility needed?

**Comment by Gitjas** [comment]
If you'd tackle the (technical) issues that would be awesome! Some kind of changelog would be useful, so the reply to your question is kind of "both".
EE compatibility is needed, yes. Thank you very much in advance, and no rush. This is not a game breaking bug.

**Comment by Sampsca** [comment]
I believe I have finished processing the existing BAMs.  I have given them a cursory glance in BGT and didn't notice anything I screwed up.  However, the issue with several of the spell items showing only a generic rolled-up scroll is that the ITM files are using a BAM that is only a generic rolled-up (note-style) scroll, and not an appropriate spell scroll.  In many cases, a type A spell item icon does not exist for that spell.  A couple use spell icons from existing spells.  I'm no artist, but I'll see what I can do.

**Comment by Gitjas** [comment]
Thank you very much!

**Comment by Sampsca** [comment]
Well I just spent a **week** working on the BAMs from the most recently released version of the mod (on SHS), and have just now realized that the BAMs in this repo are COMPLETELY different and most of what I have spent my time doing was done 5 years ago.  These BAMs have a completely different set of problems, and I'm not sure I have the motivation for another week of drudgery.  This is my own fault, but I blame the world.

**Comment by Gitjas** [comment]
Oh no, I am sorry! Put this far away, drink a hot tee or maybe better a whiskey, and do something completely different! 
This sucks.

**Comment by K4thos** [comment]
I'm not sure how that's possible. I don't remember changing the BAM files. At most I may had added DS prefix to the name if it was missing or maybe add some additional BAM from BG:EE version when I was porting some minor stuff from that version  (don't remember now, sorry). Either way going back to using BAM files from original BGT release seems like not a bad idea, if you already fixed them.

**Comment by Sampsca** [comment]
At some point someone did a significant amount of manual editing.  BAMs were renamed, bad backgrounds were replaced, items were rotated to match standard orientations, shadows were added to items, missing spell icons were created, missing sequences were added, etc.  The first time around I went frame by frame and replaced erroneous transparent and shadow pixels inside the images, and replaced non-shadow pixels inside the shadows.  I'm not really up to doing that again, but I'll redo everything else.

**Comment by Sampsca** [comment]
https://www.dropbox.com/s/4dxya0a7tjkzq8j/DSotSC_bam_v2.rar?dl=0
Completely untested.  Let me know if I broke anything.

Here's the rough changelog:
- Deleted extraneous sequences
- Added missing but necessary sequences
- Added missing shadows to item icons
- Added EE compatibility
- Ensured proper offsets of all frames
- Hyper-compressed all BAMs (which includes a wide variety of other corrections and fixes)

**Comment by Gitjas** [comment]
Thank you very much! Downloaded.

**Comment by Gitjas** [comment]
As far as I could see they are working fine. THanks again for your work!
